name: Hello

on:
  workflow_dispatch:
    inputs:
      Name:
        description: Who to greet
        required: true
        default: 'GitHub Actions'

jobs:
  Hello:
    runs-on: ubuntu-latest
    permissions:
      token: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello
        uses: ./.github/actions/hello
        with:
          Name: ${{ github.event.inputs.Name }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
